"""Element-by-element reference tests for parse_pdf().

Two reference modes:

  Scene-by-scene (default):
    ref["scenes"] — parser scene count and element order must match exactly.
    Used for parser-generated references where scene structure is known.

  Flat (ref["_meta"]["comparison"] == "flat"):
    ref["elements"] — a single ordered list of all elements across the play.
    The parser's elements are flattened (all scenes concatenated) and compared
    sequentially.  Scene count differences are ignored.  Used for independently-
    verified references where the PDF's natural scene structure differs from the
    parser's artificial scene splitting.

Element fingerprint: (kind, speaker, sig, overlap_cue?) where
    sig = first character of each whitespace-separated token, preserving case.

The test is strict on kind and speaker (attribution bugs) and sig (text shape).

xfail: set ref["_meta"]["xfail"] to a reason string to mark a known bug.

Independent attribution tests (test_independent_attribution):
  Uses *_independent.json files generated by scripts/extract_independent.py —
  NO dependency on parser.py.  Builds a sig → valid_speakers lookup table from
  the independent reference, then checks each parser element's attribution.
  Only sigs ≥ 4 characters are checked to avoid ambiguity.  Skipped silently
  when the _independent.json file is absent.

Run:
    pytest backend/tests/test_reference.py -v
    pytest backend/tests/test_reference.py -v -k TheHarvest
    pytest backend/tests/test_reference.py -v -k attribution
"""

import json
import os
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent
REF_DIR = ROOT / "Test PDFs" / "reference"
PDF_DIR = ROOT / "Test PDFs"

sys.path.insert(0, str(ROOT / "backend"))
from parser import parse_pdf  # noqa: E402


def _sig(text: str) -> str:
    """First character of each whitespace-separated token, preserving case."""
    return "".join(w[0] for w in (text or "").split() if w)


def _load_ref(name: str) -> dict:
    with open(REF_DIR / f"{name}.json", encoding="utf-8") as f:
        return json.load(f)


def _flatten_ref(ref: dict) -> list[dict]:
    """Return flat element list regardless of ref format."""
    if "elements" in ref:
        return ref["elements"]
    return [el for scene in ref["scenes"] for el in scene["elements"]]


CASES = [
    ("TheHarvest",         "TheHarvest(3.0).pdf"),
    ("KillFloor",          "Kill Floor (LCT Reading Draft).pdf"),
    ("AgainstTheHillside", "Against the Hillside 11.20.17.pdf"),
    ("NoneOfUs",           "5.0 None of Us Are Getting Out of This Alive (2).pdf"),
    ("MercuryFur",         "Mercury Fur-13 f Draft-June 10-2013.pdf"),
    ("EMMA",               "EMMA Script (2).pdf"),
    ("Stereophonic",       "4.10.24_Stereophonic (2).pdf"),
]


def _compare_flat(
    ref_name: str,
    ref_els: list[dict],
    parser_els: list,
) -> list[str]:
    failures: list[str] = []

    if len(ref_els) != len(parser_els):
        failures.append(
            f"Element count: expected {len(ref_els)}, got {len(parser_els)}"
        )

    for el_idx, (ref_el, parser_el) in enumerate(zip(ref_els, parser_els)):
        loc = f"el {el_idx}"

        if ref_el["kind"] != parser_el.kind:
            failures.append(
                f"{loc}: kind expected {ref_el['kind']!r}, "
                f"got {parser_el.kind!r}  sig={ref_el['sig'][:20]!r}"
            )

        if ref_el["speaker"] != parser_el.speaker:
            failures.append(
                f"{loc}: speaker expected {ref_el['speaker']!r}, "
                f"got {parser_el.speaker!r}  "
                f"kind={ref_el['kind']}  sig={ref_el['sig'][:20]!r}"
            )

        parser_sig = _sig(parser_el.text)
        if ref_el["sig"] != parser_sig:
            failures.append(
                f"{loc}: sig expected {ref_el['sig'][:30]!r}, "
                f"got {parser_sig[:30]!r}  "
                f"speaker={ref_el['speaker']}  kind={ref_el['kind']}"
            )

        ref_overlap = ref_el.get("overlap_cue")
        parser_overlap = parser_el.overlap_cue
        if ref_overlap != parser_overlap:
            failures.append(
                f"{loc}: overlap_cue expected {ref_overlap!r}, "
                f"got {parser_overlap!r}"
            )

    return failures


def _compare_scenes(
    ref_name: str,
    ref: dict,
    script,
) -> list[str]:
    failures: list[str] = []

    if len(script.scenes) != len(ref["scenes"]):
        failures.append(
            f"Scene count: expected {len(ref['scenes'])}, got {len(script.scenes)}"
        )

    for ref_scene, parser_scene in zip(ref["scenes"], script.scenes):
        ref_els = ref_scene["elements"]
        parser_els = parser_scene.elements
        scene_label = f"Scene {ref_scene['number']} ({ref_scene['title']!r})"

        if len(ref_els) != len(parser_els):
            failures.append(
                f"{scene_label}: element count expected {len(ref_els)}, "
                f"got {len(parser_els)}"
            )

        for el_idx, (ref_el, parser_el) in enumerate(zip(ref_els, parser_els)):
            loc = f"{scene_label} el {el_idx}"

            if ref_el["kind"] != parser_el.kind:
                failures.append(
                    f"{loc}: kind expected {ref_el['kind']!r}, "
                    f"got {parser_el.kind!r}  sig={ref_el['sig'][:20]!r}"
                )

            if ref_el["speaker"] != parser_el.speaker:
                failures.append(
                    f"{loc}: speaker expected {ref_el['speaker']!r}, "
                    f"got {parser_el.speaker!r}  "
                    f"kind={ref_el['kind']}  sig={ref_el['sig'][:20]!r}"
                )

            parser_sig = _sig(parser_el.text)
            if ref_el["sig"] != parser_sig:
                failures.append(
                    f"{loc}: sig expected {ref_el['sig'][:30]!r}, "
                    f"got {parser_sig[:30]!r}  "
                    f"speaker={ref_el['speaker']}  kind={ref_el['kind']}"
                )

            ref_overlap = ref_el.get("overlap_cue")
            parser_overlap = parser_el.overlap_cue
            if ref_overlap != parser_overlap:
                failures.append(
                    f"{loc}: overlap_cue expected {ref_overlap!r}, "
                    f"got {parser_overlap!r}"
                )

    return failures


@pytest.mark.parametrize("ref_name,pdf_name", CASES)
def test_reference(ref_name: str, pdf_name: str) -> None:
    pdf_path = str(PDF_DIR / pdf_name)
    if not os.path.exists(pdf_path):
        pytest.skip(f"PDF not found: {pdf_path}")

    ref_path = REF_DIR / f"{ref_name}.json"
    if not ref_path.exists():
        pytest.skip(f"Reference not found: {ref_path}")

    ref = _load_ref(ref_name)

    xfail_reason = ref.get("_meta", {}).get("xfail")
    if xfail_reason:
        pytest.xfail(xfail_reason)

    script = parse_pdf(pdf_path)

    flat_mode = ref.get("_meta", {}).get("comparison") == "flat"

    if flat_mode:
        ref_els = _flatten_ref(ref)
        parser_els = [el for scene in script.scenes for el in scene.elements]
        failures = _compare_flat(ref_name, ref_els, parser_els)
    else:
        failures = _compare_scenes(ref_name, ref, script)

    if failures:
        MAX_SHOWN = 30
        shown = failures[:MAX_SHOWN]
        tail = (
            f"\n  ... and {len(failures) - MAX_SHOWN} more"
            if len(failures) > MAX_SHOWN
            else ""
        )
        pytest.fail(
            f"\n\nReference failures for {ref_name} "
            f"({len(failures)} total):\n"
            + "\n".join(f"  • {f}" for f in shown)
            + tail
        )


# ---------------------------------------------------------------------------
# Independent attribution tests
#
# Uses *_independent.json files generated by scripts/extract_independent.py —
# no dependency on parser.py.  Builds a sig → valid_speakers lookup from the
# independent reference (sigs ≥ 4 chars only, to avoid ambiguous 1-char sigs),
# then checks each parser element's attribution against it.
#
# This test is separate from test_reference because it doesn't require element
# count parity — the independent extractor creates one element per PDF line,
# while the parser merges continuation lines.  The sig-lookup approach works
# regardless of that difference.
# ---------------------------------------------------------------------------

_ATTRIBUTION_CASES = [
    ("TheHarvest",  "TheHarvest(3.0).pdf"),
    ("KillFloor",   "Kill Floor (LCT Reading Draft).pdf"),
    ("NoneOfUs",    "5.0 None of Us Are Getting Out of This Alive (2).pdf"),
    ("MercuryFur",  "Mercury Fur-13 f Draft-June 10-2013.pdf"),
]

_MIN_SIG_LEN = 4  # shorter sigs are too ambiguous for reliable attribution check


def _build_sig_lookup(ind_elements: list[dict]) -> tuple[dict[str, set], list[str]]:
    """Build (exact_lookup, sigs_by_len_desc) from independent reference dialog elements.

    exact_lookup: sig → set of valid speakers
    sigs_by_len_desc: independent sigs sorted by decreasing length (for prefix matching)

    The parser merges continuation lines, producing sigs like "FMwhfHs" from two
    independent lines "FMwhf" + "Hs".  Prefix matching catches these cases: if a
    parser sig starts with an independent sig, that's a valid match.
    """
    exact_lookup: dict[str, set] = {}
    for el in ind_elements:
        if el.get("kind") != "dialog":
            continue
        s = el.get("sig", "")
        if len(s) < _MIN_SIG_LEN:
            continue
        exact_lookup.setdefault(s, set()).add(el.get("speaker"))
    # Sort descending by length so longest prefix takes priority in lookups
    sigs_by_len_desc = sorted(exact_lookup.keys(), key=len, reverse=True)
    return exact_lookup, sigs_by_len_desc


def _lookup_attribution(
    parser_sig: str,
    exact_lookup: dict[str, set],
    sigs_by_len_desc: list[str],
) -> set | None:
    """Return valid speakers for parser_sig, or None if not found.

    Tries exact match first, then prefix match (independent sig is a prefix of
    parser sig — handles merged continuation lines).
    """
    if parser_sig in exact_lookup:
        return exact_lookup[parser_sig]
    for ind_sig in sigs_by_len_desc:
        if parser_sig.startswith(ind_sig):
            return exact_lookup[ind_sig]
    return None


@pytest.mark.parametrize("ref_name,pdf_name", _ATTRIBUTION_CASES)
def test_independent_attribution(ref_name: str, pdf_name: str) -> None:
    """Check parser speaker attribution against independently-read reference.

    For each parser dialog element whose sig can be matched in the independent
    reference (exact or prefix match), the parser's attributed speaker must be
    in the set of valid speakers for that sig.

    Only sigs ≥ 4 characters are checked to avoid ambiguous 1-3 char sigs.
    """
    pdf_path = str(PDF_DIR / pdf_name)
    if not os.path.exists(pdf_path):
        pytest.skip(f"PDF not found: {pdf_path}")

    ind_path = REF_DIR / f"{ref_name}_independent.json"
    if not ind_path.exists():
        pytest.skip(f"Independent reference not found: {ind_path}")

    with open(ind_path, encoding="utf-8") as f:
        ind_ref = json.load(f)

    exact_lookup, sigs_by_len_desc = _build_sig_lookup(ind_ref.get("elements", []))

    script = parse_pdf(pdf_path)
    parser_els = [el for scene in script.scenes for el in scene.elements]

    checked = 0
    failures: list[str] = []

    for el_idx, el in enumerate(parser_els):
        if el.kind != "dialog":
            continue
        s = _sig(el.text)
        if len(s) < _MIN_SIG_LEN:
            continue
        valid_speakers = _lookup_attribution(s, exact_lookup, sigs_by_len_desc)
        if valid_speakers is None:
            continue
        checked += 1
        if el.speaker not in valid_speakers:
            failures.append(
                f"el {el_idx}: speaker={el.speaker!r} not in {valid_speakers!r}  "
                f"sig={s[:30]!r}"
            )

    total_dialog = sum(1 for el in parser_els if el.kind == "dialog")
    coverage = checked / total_dialog if total_dialog else 0.0

    if failures:
        MAX_SHOWN = 30
        shown = failures[:MAX_SHOWN]
        tail = (
            f"\n  ... and {len(failures) - MAX_SHOWN} more"
            if len(failures) > MAX_SHOWN
            else ""
        )
        pytest.fail(
            f"\n\nIndependent attribution failures for {ref_name} "
            f"({len(failures)} wrong / {checked} checked / {total_dialog} dialog "
            f"/ {coverage:.0%} coverage):\n"
            + "\n".join(f"  • {f}" for f in shown)
            + tail
        )

    print(
        f"\n  [{ref_name}] independent attribution: "
        f"{checked}/{total_dialog} dialog checked ({coverage:.0%} coverage), "
        f"{len(failures)} failures"
    )
