#if os(iOS)
import Foundation

// MARK: - Kokoro ONNX TTS engine
//
// Requires the ONNX Runtime Swift package — see ios-setup instructions in the repo.
// SPM: https://github.com/microsoft/onnxruntime-swift-package-manager  tag ≥ 1.20.0
// Xcode: File → Add Package Dependencies, then add `onnxruntime` to the iOS target.
//
// Model files (downloaded on first use, cached in ~/Library/Application Support/TableRead/):
//   kokoro-v1.0.int8.onnx  — ~88 MB inference model
//   kokoro-voices/          — per-voice .kokoro embeddings (~511 KB each)
//                             generated by scripts/convert_kokoro_voices.py

#if canImport(OnnxRuntime)
import OnnxRuntime
#endif

// MARK: - Model path helpers

private enum KokoroPaths {
    static var appSupport: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("TableRead")
    }
    static var modelURL: URL {
        appSupport.appendingPathComponent("kokoro-v1.0.int8.onnx")
    }
    static let modelDownloadURL = URL(
        string: "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.int8.onnx"
    )!
}

// MARK: - Engine

/// Neural TTS via Kokoro-82M (Apache-2.0) running on ONNX Runtime for iOS.
///
/// Audio quality is comparable to the macOS Kokoro engine since both use the
/// same ONNX model. No internet connection is required after the initial download.
///
/// Phonemization is handled by a pluggable `G2PConverter`. The default
/// (`RuleBasedG2P`) covers common English vocabulary well enough for testing;
/// wire in an espeak-ng bridge for production quality (see `EspeakG2P.swift`).
actor KokoroONNXEngine: IOSTTSEngine {
    let name = "Kokoro (local neural)"
    let audioExtension = ".wav"

    private let g2p: any G2PConverter
    private let voiceStore = KokoroVoiceStore()

    /// Memoised ONNX session — loaded lazily on first synthesis call.
    private var _session: AnyObject? // ORTSession when OnnxRuntime is available

    // MARK: - Known voices (mirrors KokoroEngine.VOICES in tts_engines.py)

    static let voices: [IOSVoiceInfo] = [
        IOSVoiceInfo(id: "af_heart",    label: "Heart",    gender: "F", locale: "en_US", note: "warm narrator"),
        IOSVoiceInfo(id: "af_alloy",    label: "Alloy",    gender: "F", locale: "en_US", note: "neutral"),
        IOSVoiceInfo(id: "af_aoede",    label: "Aoede",    gender: "F", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "af_bella",    label: "Bella",    gender: "F", locale: "en_US", note: "expressive"),
        IOSVoiceInfo(id: "af_jessica",  label: "Jessica",  gender: "F", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "af_kore",     label: "Kore",     gender: "F", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "af_nicole",   label: "Nicole",   gender: "F", locale: "en_US", note: "asmr"),
        IOSVoiceInfo(id: "af_nova",     label: "Nova",     gender: "F", locale: "en_US", note: "bright"),
        IOSVoiceInfo(id: "af_river",    label: "River",    gender: "F", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "af_sarah",    label: "Sarah",    gender: "F", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "af_sky",      label: "Sky",      gender: "F", locale: "en_US", note: "bright"),
        IOSVoiceInfo(id: "am_adam",     label: "Adam",     gender: "M", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "am_echo",     label: "Echo",     gender: "M", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "am_eric",     label: "Eric",     gender: "M", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "am_fenrir",   label: "Fenrir",   gender: "M", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "am_liam",     label: "Liam",     gender: "M", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "am_michael",  label: "Michael",  gender: "M", locale: "en_US", note: "warm"),
        IOSVoiceInfo(id: "am_onyx",     label: "Onyx",     gender: "M", locale: "en_US", note: "deep"),
        IOSVoiceInfo(id: "am_puck",     label: "Puck",     gender: "M", locale: "en_US", note: nil),
        IOSVoiceInfo(id: "bf_alice",    label: "Alice",    gender: "F", locale: "en_GB", note: nil),
        IOSVoiceInfo(id: "bf_emma",     label: "Emma",     gender: "F", locale: "en_GB", note: nil),
        IOSVoiceInfo(id: "bf_isabella", label: "Isabella", gender: "F", locale: "en_GB", note: nil),
        IOSVoiceInfo(id: "bf_lily",     label: "Lily",     gender: "F", locale: "en_GB", note: nil),
        IOSVoiceInfo(id: "bm_daniel",   label: "Daniel",   gender: "M", locale: "en_GB", note: "narrator"),
        IOSVoiceInfo(id: "bm_fable",    label: "Fable",    gender: "M", locale: "en_GB", note: "narrator"),
        IOSVoiceInfo(id: "bm_george",   label: "George",   gender: "M", locale: "en_GB", note: nil),
        IOSVoiceInfo(id: "bm_lewis",    label: "Lewis",    gender: "M", locale: "en_GB", note: nil),
    ]

    init(g2p: any G2PConverter = RuleBasedG2P()) {
        self.g2p = g2p
    }

    func isAvailable() -> Bool {
        FileManager.default.fileExists(atPath: KokoroPaths.modelURL.path)
    }

    func listVoices() -> [IOSVoiceInfo] {
        Self.voices
    }

    // MARK: - Synthesis

    func synthesize(text: String, voiceID: String, outputURL: URL) async throws {
        guard isAvailable() else { throw IOSTTSError.modelNotLoaded }

        // Phonemize → token IDs
        let lang = voiceID.hasPrefix("b") ? "en-gb" : "en-us"
        let phonemes = g2p.phonemize(text, lang: lang)
        var tokens = KokoroVocab.tokenize(phonemes)

        guard !tokens.isEmpty else {
            throw IOSTTSError.synthesisFailure("Phonemization produced no tokens for: \(text.prefix(40))")
        }

        // Clamp to max context (510 tokens before padding)
        if tokens.count > 510 { tokens = Array(tokens.prefix(510)) }

        // Get style vector: voice[tokenCount] row, shape [256]
        let styleVec = try await voiceStore.styleVector(for: voiceID, tokenCount: tokens.count)

        // Pad tokens: [0, ...tokens, 0]
        var paddedTokens = [Int64(0)] + tokens + [Int64(0)]

        // Run ONNX inference
        let audioSamples = try runInference(
            tokens: &paddedTokens,
            style: styleVec,
            speed: 1.0
        )

        // Write 16-bit WAV at 24 kHz
        try writeWAV(samples: audioSamples, sampleRate: 24000, outputURL: outputURL)
    }

    // MARK: - ONNX inference

    private func runInference(
        tokens: inout [Int64],
        style: [Float],
        speed: Float
    ) throws -> [Float] {
#if canImport(OnnxRuntime)
        let session = try getOrCreateSession()

        // tokens tensor: int64 [1, seqLen]
        let seqLen = tokens.count
        let tokenTensor = try ORTValue(
            tensorData: NSMutableData(
                bytes: &tokens,
                length: seqLen * MemoryLayout<Int64>.stride
            ),
            elementType: .int64,
            shape: [1, NSNumber(value: seqLen)]
        )

        // style tensor: float32 [1, 256]
        var styleMut = style
        let styleTensor = try ORTValue(
            tensorData: NSMutableData(
                bytes: &styleMut,
                length: styleMut.count * MemoryLayout<Float>.stride
            ),
            elementType: .float,
            shape: [1, 256]
        )

        // speed tensor: float32 [1]
        var speedVal = speed
        let speedTensor = try ORTValue(
            tensorData: NSMutableData(bytes: &speedVal, length: MemoryLayout<Float>.stride),
            elementType: .float,
            shape: [1]
        )

        // Determine input name — older exports use "tokens", newer use "input_ids"
        let inputInfo = try session.inputNames()
        let tokenInputName = inputInfo.contains("input_ids") ? "input_ids" : "tokens"

        let outputs = try session.run(
            withInputs: [
                tokenInputName: tokenTensor,
                "style": styleTensor,
                "speed": speedTensor,
            ],
            outputNames: ["audio"],
            runOptions: nil
        )

        let audioData = try outputs["audio"]!.tensorData() as Data
        let sampleCount = audioData.count / MemoryLayout<Float>.size
        return audioData.withUnsafeBytes { ptr in
            Array(ptr.bindMemory(to: Float.self).prefix(sampleCount))
        }
#else
        throw IOSTTSError.modelNotLoaded
#endif
    }

#if canImport(OnnxRuntime)
    private func getOrCreateSession() throws -> ORTSession {
        if let existing = _session as? ORTSession { return existing }
        let env = try ORTEnvironment(loggingLevel: .warning)
        let opts = try ORTSessionOptions()
        let session = try ORTSession(
            env: env,
            modelPath: KokoroPaths.modelURL.path,
            sessionOptions: opts
        )
        _session = session
        return session
    }
#endif

    // MARK: - WAV writing

    /// Writes float32 PCM samples to a standard 16-bit mono WAV file.
    private func writeWAV(samples: [Float], sampleRate: Int, outputURL: URL) throws {
        let numSamples = samples.count
        let bitsPerSample: Int = 16
        let numChannels: Int = 1
        let byteRate = sampleRate * numChannels * bitsPerSample / 8
        let dataSize = numSamples * numChannels * bitsPerSample / 8
        let fileSize = 44 + dataSize

        var header = Data(capacity: 44)
        func appendUInt32LE(_ v: UInt32) { withUnsafeBytes(of: v.littleEndian) { header.append(contentsOf: $0) } }
        func appendUInt16LE(_ v: UInt16) { withUnsafeBytes(of: v.littleEndian) { header.append(contentsOf: $0) } }

        header.append(contentsOf: "RIFF".utf8)
        appendUInt32LE(UInt32(fileSize - 8))
        header.append(contentsOf: "WAVE".utf8)
        header.append(contentsOf: "fmt ".utf8)
        appendUInt32LE(16)                             // chunk size
        appendUInt16LE(1)                              // PCM format
        appendUInt16LE(UInt16(numChannels))
        appendUInt32LE(UInt32(sampleRate))
        appendUInt32LE(UInt32(byteRate))
        appendUInt16LE(UInt16(numChannels * bitsPerSample / 8))  // block align
        appendUInt16LE(UInt16(bitsPerSample))
        header.append(contentsOf: "data".utf8)
        appendUInt32LE(UInt32(dataSize))

        // Convert float32 [-1,1] → int16
        var pcm = Data(capacity: dataSize)
        for s in samples {
            let clamped = max(-1.0, min(1.0, s))
            let int16 = Int16(clamped * 32767)
            withUnsafeBytes(of: int16.littleEndian) { pcm.append(contentsOf: $0) }
        }

        var output = header
        output.append(pcm)
        try output.write(to: outputURL, options: .atomic)
    }
}

// MARK: - Download support

extension KokoroONNXEngine {
    /// Downloads the Kokoro ONNX model to Application Support if not already present.
    /// Progress callbacks fire on the calling actor's executor.
    func downloadModelIfNeeded(progress: @Sendable @escaping (Double) -> Void) async throws {
        guard !isAvailable() else { return }

        let dest = KokoroPaths.modelURL
        try FileManager.default.createDirectory(
            at: dest.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        let (tempURL, response) = try await URLSession.shared.download(from: KokoroPaths.modelDownloadURL)
        guard let http = response as? HTTPURLResponse, http.statusCode == 200 else {
            throw IOSTTSError.synthesisFailure("Model download failed")
        }
        if FileManager.default.fileExists(atPath: dest.path) {
            try FileManager.default.removeItem(at: dest)
        }
        try FileManager.default.moveItem(at: tempURL, to: dest)
    }
}
#endif
